version: '2'
services:

  db:
    ports:
      - "5432:5432"

  backend:
    image: localhost:5000/bit-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - EXEC=start
    volumes:
      - ./${ENVIRONMENT}/backend_data/upload:/app/upload
      - ./${ENVIRONMENT}/backend_data/tmp:/app/tmp
    depends_on:
      - db
  
  proxy:
    depends_on:
      - backend
    volumes:
      - ./configuration/deployment/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./configuration/deployment/ssl/:/etc/ssl/
    env_file:
      - ./configuration/deployment/config
    ports:
      - 80:80
      - 443:443